name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run with Docker Compose
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from crophealth-app
