name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure `data/aoi` folder exists
        run: mkdir -p data/aoi

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build Docker containers
        run: |
          docker-compose -f docker-compose.yml build

      - name: Run pipeline
        run: |
          docker-compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from app
