name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure data folders exist (writable for container)
        run: |
          mkdir -p data/aoi data/processed data/raw_landsat
          chmod -R 777 data

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker containers
        run: |
          docker-compose -f docker-compose.yml build

      - name: Run pipeline
        run: |
          docker-compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from app
