name: Local Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-local:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgis/postgis:15-3.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345
          POSTGRES_DB: Crop_Health
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d Crop_Health"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=20

    env:
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
      POSTGRES_DB: Crop_Health
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install psql client and wait for DB
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client
          for i in {1..30}; do
            pg_isready -h 127.0.0.1 -p 5432 -d Crop_Health -U postgres && echo "DB is ready" && break
            echo "waiting for db ($i/30)..." && sleep 2
          done

      - name: Prepare data dirs
        run: |
          mkdir -p data/aoi data/processed data/raw_landsat

      - name: Run pipeline (local)
        run: |
          python main.py
